version: "3"
services: 
  app:
    build: .
    ports: 
      - "8080:8080"
    environment:
      - MYSQL_PASSWORD=development
      - MYSQL_DATABASE=albion
      - MYSQL_USER=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - AUTH_PASSWORD=test
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=development
      - MYSQL_DATABASE=albion
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined